id: 83b4ef64-9af6-4bec-9707-674fa82c2837
# Sets the URL name of the quickstart on public I/O (required)
slug: etcd

# Displayed in the UI (required)
title: Etcd (Prometheus)

# Long-form description of the quickstart (required)
description: |
 ## What is Etcd?

 Etcd is a strongly consistent, distributed key-value store that provides a reliable way to store data that needs to be accessed by a distributed system or cluster of machines. It gracefully handles leader elections during network partitions and can tolerate machine failure, even in the leader node

 ## Quickstart details

 This quickstart was built based on Etcd metrics sent to New Relic through remote write configurations with Prometheus Agent or Prometheus server.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  A curated dashboard based on Prometheus metrics which helps you understand the health of your Etcd cluster.  This quickstart was built based on `etcd` metrics sent to New Relic through remote write configurations with Prometheus Agent or Prometheus server.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - New Relic
  - Brad Schmitt
  - Raga Potti

# Keywords for filtering / searching criteria in the UI
keywords:
  - etcd
  - kubernetes
  - k8s
  - prometheus
  - remote-write
  - featured

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - setup-prometheus
  - setup-prometheus-agent-mode

dashboards:
  - etcd

alertPolicies:
  - etcd

# Documentation references
documentation:
  - name: Prometheus installation docs
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/
    description: Use Prometheus remote_write or Prometheus Agent
  - name: Etcd Metrics Documentation
    url: https://etcd.io/docs/v3.5/metrics/
    description: Learn more about the Prometheus metrics available for Etcd

# Content / Design
icon: logo.png
website: https://etcd.io/
