# Name of the quickstart (required)
id: c9ac4abb-4a61-4eee-9e1e-79506806684e
slug: coredns

# Displayed in the UI (required)
title: CoreDNS (Prometheus)

# Long-form description of the quickstart (required)
description: |
  The CoreDNS quickstart includes a dashboard and set of alerts that provides a holistic view of the CoreDNS instances in your environment. Information contained in the dasshboard includes CoreDNS versions, status, request/response times, and cache statistics. This quickstart was built and tested based on CoreDNS metrics sent to New Relic through remote write configurations with Prometheus Agent or Prometheus Server.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Easily install a curated dashboard and alerts to monitor the health of your CoreDNS instances. This quickstart was built and tested based on CoreDNS metrics sent to New Relic through remote write configurations with Prometheus Agent or Prometheus Server.

# Support level: New Relic | Verified | Community (required)
level: Verified

# Authors of the quickstart (required)
authors:
  - New Relic
  - Brad Schmitt
  - Raga Potti

# Keywords for filtering / searching criteria in the UI
keywords:
  - coredns
  - prometheus
  - remote write
  - remote_write
  - remote-write
  - promql
  - grafana
  - featured

documentation:
  - name: Prometheus installation docs
    description: |
      Use Prometheus remote_write or Prometheus Agent
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/

alertPolicies:
  - coredns

installPlans:
  - setup-prometheus
  - setup-prometheus-agent-mode

# Content / Design
icon: coredns-logo.png

dashboards:
  - coredns
